import turtle
t = turtle.Turtle()
turtle.Screen().bgcolor('black')
turtle.title("Facebook")
t.pensize(5)
t.hideturtle()


def gt(x=0, y=0, z=0):
    t.pu()
    t.goto(x, y)
    t.fd(z)
    t.pendown()


t.fillcolor("blue")
t.begin_fill()
gt(-15, -80)
t.circle(102)
t.end_fill()
gt(-27, -78)
t.fillcolor("white")
t.pensize(3)
t.begin_fill()
t.lt(90)
t.fd(150)
t.rt(90)
t.fd(60)
for i in range(2):
    t.rt(90)
    t.fd(30)
t.lt(90)
t.fd(120)
t.rt(90)
t.end_fill()
gt(32, 20)
t.fillcolor("white")
t.begin_fill()
t.fd(29)
gt(3, 20, 30)
t.fd(20)
t.lt(90)
t.fd(30)
t.lt(90)
t.fd(20)
gt(-27, -10, 30)
t.fd(24)
t.goto(32, 20)
t.end_fill()
t.color('red')
gt(-250, 165)
t.write("#MarkHasRead", font=('Comic Sans MS', 48, ''))
turtle.done()
